In [1]:
import pandas as pd
import numpy as np

In [2]:
# use the second file
data1_1 = pd.read_csv("20220808-FULL-1_1.csv", sep=';')
# display the data
data1_1

C:\Users\JXN19\AppData\Local\Temp/ipykernel_15964/1951926038.py:2: DtypeWarning: Columns (5,36,86,89) have mixed types. Specify dtype option on import or set low_memory=False.
  data1_1 = pd.read_csv("20220808-FULL-1_1.csv", sep=';')


fileGenerationDate  Entity_LogicalId Entity_EU_ReferenceNumber  \
0             08/08/2022                13                  EU.27.28   
1             08/08/2022                13                  EU.27.28   
2             08/08/2022                13                  EU.27.28   
3             08/08/2022                13                  EU.27.28   
4             08/08/2022                13                  EU.27.28   
...                  ...               ...                       ...   
21790         08/08/2022            143389                EU.8692.54   
21791         08/08/2022            143389                EU.8692.54   
21792         08/08/2022            143389                EU.8692.54   
21793         08/08/2022            143389                EU.8692.54   
21794         08/08/2022            143389                EU.8692.54   

      Entity_UnitedNationId Entity_DesignationDate Entity_DesignationDetails  \
0                       NaN                    NaN                       NaN   
1                       NaN                    NaN                       NaN   
2                       NaN                    NaN                       NaN   
3                       NaN                    NaN                       NaN   
4                       NaN                    NaN                       NaN   
...                     ...                    ...                       ...   
21790                   NaN             2022-07-21                       NaN   
21791                   NaN             2022-07-21                       NaN   
21792                   NaN             2022-07-21                       NaN   
21793                   NaN             2022-07-21                       NaN   
21794                   NaN             2022-07-21                       NaN   

                              Entity_Remark Entity_SubjectType  \
0                    (UNSC RESOLUTION 1483)                  P   
1                    (UNSC RESOLUTION 1483)                  P   
2                    (UNSC RESOLUTION 1483)                  P   
3                    (UNSC RESOLUTION 1483)                  P   
4                    (UNSC RESOLUTION 1483)                  P   
...                                     ...                ...   
21790  (Date of UN designation: 2022-07-21)                  P   
21791  (Date of UN designation: 2022-07-21)                  P   
21792  (Date of UN designation: 2022-07-21)                  P   
21793  (Date of UN designation: 2022-07-21)                  P   
21794  (Date of UN designation: 2022-07-21)                  P   

      Entity_SubjectType_ClassificationCode Entity_Regulation_Type  ...  \
0                                    person             regulation  ...   
1                                    person             regulation  ...   
2                                    person             regulation  ...   
3                                    person             regulation  ...   
4                                    person             regulation  ...   
...                                     ...                    ...  ...   
21790                                person              amendment  ...   
21791                                person              amendment  ...   
21792                                person              amendment  ...   
21793                                person              amendment  ...   
21794                                person              amendment  ...   

      Citizenship_LogicalId Citizenship_RegulationLanguage Citizenship_Remark  \
0                       NaN                            NaN                NaN   
1                       NaN                            NaN                NaN   
2                       NaN                            NaN                NaN   
3                       NaN                            NaN                NaN   
4                       1.0                             EN                NaN   


In [3]:
# get the whole name attribute
whole_name = data1_1['NameAlias_WholeName']

In [4]:
def cp(C,D):
    cend=[]
    a=-1
    b=-1
    m=-1
    n=-1
    target=-1
    if C==''and D=='':
        s=0
    elif C=='':
        s=0
    elif D=='':
        s=1    
    else:
        for i in range(len(C)):
            t=1
            for j in range(len(D)):
                if C[i]== D[j]:
                    a=i
                    b=j
                    m=a
                    n=b
                while m < len(C) and n<len(D) and C[a:m+1]==D[b:n+1]:
                    m=m+1
                    n=n+1
                long=m-a
                if long >= t:
                    t = long
                    target = m
            
            x=target-1
            y=n-1
            if b <len(D) and C[i]==D[b] :
                cend.append(x)
            else:
                cend.append(i)
        s_AB = len(set(cend))
        z = C.find(D);
        if z!=-1:
            ss=s_AB-1;
        else:
            ss = s_AB
        s=ss/len(C)    
    return s     

In [5]:
def distCPD(C,D):
    s1 = cp(C,D);
    s2 = cp(D,C);
    dist = 0.5*(s1+s2);
    return dist

In [6]:
len(whole_name)

21795

In [7]:
# so I replaced them with empty strings
whole_name.fillna('', inplace=True)
whole_name

0             Saddam Hussein Al-Tikriti
1                               Abu Ali
2                              Abou Ali
3                                      
4                                      
                      ...              
21790       Евгений Витальевич БАЛИЦКИЙ
21791    Yevgeniy Vitalievich BALYTSKIY
21792    Jevgenij Vitaljevitj BALITSKIJ
21793                                  
21794                                  
Name: NameAlias_WholeName, Length: 21795, dtype: object

In [8]:
import numpy as np
index = [i for i in range(len(whole_name))] # test_data为测试数据
np.random.shuffle(index) # 打乱索引
train_data = whole_name[index]

In [9]:
train_data

3822                  Reymund Lavilla
11925                    CHUN SONG RI
20775                                
196       Humam 'Abd-al-Khaliq Rashid
15828    Игорь  Анатольевич  МАРШАЛОВ
                     ...             
4944                                 
14873         Maksim Yurevich FILATOV
21401                                
18429      Viktor Viktororvich ZOBNEV
12358                                
Name: NameAlias_WholeName, Length: 21795, dtype: object

In [10]:
# calculate all the distances in whole_name
length_train =  int(0.1*len(whole_name))
Name = np.zeros((length_train,length_train))
for i in range(length_train):
    for j in range(i+1,length_train):
        Name[i][j]=distCPD(train_data[i],train_data[j])

In [11]:
Name

array([[0.        , 0.72571429, 0.7725    , ..., 0.5       , 0.5       ,
        0.93833333],
       [0.        , 0.        , 0.33035714, ..., 0.5       , 0.5       ,
        0.88690476],
       [0.        , 0.        , 0.        , ..., 0.5       , 0.5       ,
        0.89583333],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.5       ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.5       ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [12]:
Name.shape

(2179, 2179)

In [13]:
index

[3822,
 11925,
 20775,
 196,
 15828,
 17926,
 12344,
 14297,
 19271,
 20306,
 16049,
 18256,
 19290,
 4940,
 20107,
 10456,
 15993,
 14902,
 2603,
 12989,
 11004,
 10343,
 17026,
 10922,
 2492,
 10376,
 3282,
 5469,
 5004,
 9230,
 18483,
 19756,
 17723,
 14728,
 11382,
 5714,
 13632,
 1806,
 19464,
 13369,
 20233,
 12940,
 19786,
 8677,
 1163,
 12580,
 11497,
 12793,
 4847,
 15819,
 14738,
 7929,
 18043,
 13207,
 15946,
 13406,
 4782,
 5451,
 15855,
 13228,
 9957,
 2134,
 14907,
 15235,
 4088,
 11054,
 12108,
 3375,
 13954,
 17018,
 696,
 17505,
 10454,
 8899,
 14669,
 5760,
 13763,
 16535,
 4117,
 13740,
 13852,
 11414,
 4712,
 6659,
 7223,
 11145,
 19200,
 2958,
 8236,
 2163,
 6868,
 11734,
 16159,
 8555,
 10153,
 7108,
 9493,
 4677,
 20014,
 1339,
 465,
 10100,
 16167,
 12398,
 7793,
 73,
 4497,
 9503,
 2892,
 8150,
 8449,
 9934,
 1912,
 21496,
 18788,
 3413,
 18042,
 18054,
 18280,
 368,
 720,
 1816,
 21535,
 12857,
 5030,
 3536,
 3072,
 16719,
 4640,
 12597,
 5484,
 2294,
 3157,
 

In [14]:
entity=data1_1['Entity_LogicalId']
entity

0            13
1            13
2            13
3            13
4            13
          ...  
21790    143389
21791    143389
21792    143389
21793    143389
21794    143389
Name: Entity_LogicalId, Length: 21795, dtype: int64

In [15]:
entity_train=[]
for i in range(length_train):
    entity_train.append(entity[index[i]])

In [16]:
label = np.zeros((length_train,length_train))
for i in range(length_train):
    for j in range(i+1,length_train):
        if entity_train[i]==entity_train[j]:
            label[i][j]=0
        else:
            label[i][j] =1
print(label)        

[[0. 1. 1. ... 1. 1. 1.]
 [0. 0. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]
 ...
 [0. 0. 0. ... 0. 1. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]]


In [17]:
np.count_nonzero(label[1])

2177

In [18]:
len(set(entity_train))

1453

In [19]:
distlist=[]
for i in range(length_train):
    for j in range(i+1,length_train):
        if label[i][j]==0:
            distlist.append(Name[i][j])
print(distlist)            

[0.5, 0.9158986175115207, 0.5, 0.5, 0.0, 0.0, 0.7764976958525346, 0.8748778103616813, 0.5, 0.0, 0.5087386018237082, 0.5, 0.8280701754385965, 0.5, 0.7771883289124668, 0.8839285714285714, 1.0, 0.9511904761904761, 0.9261904761904762, 0.8898809523809523, 0.5, 0.8809523809523809, 0.5, 0.8713450292397661, 0.8454106280193237, 0.9307458143074581, 0.9087301587301587, 0.5, 0.5, 0.8669467787114846, 0.0, 0.8831168831168831, 0.5515151515151515, 0.5, 0.5, 0.7103703703703703, 0.8485838779956427, 0.8814814814814815, 0.6594202898550725, 0.8112535612535612, 0.5, 0.8897435897435897, 0.9470588235294117, 0.5, 0.9416666666666667, 0.9333333333333333, 0.5, 0.0, 0.5, 0.5, 0.5, 0.5, 0.0, 0.0, 0.5, 1.0, 0.8354037267080745, 0.8036684782608696, 0.7294685990338164, 0.5, 0.0, 0.5, 0.5, 0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.9254629629629629, 0.7836538461538461, 1.0, 0.5, 0.758098223615465, 0.8333333333333334, 0.961038961038961, 0.9134199134199135, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.9695852534562213, 0.9005376344086022, 0

In [20]:
sum(distlist)/len(distlist)

0.6367026407950206

In [21]:
datasimple=[round(i,1) for i in distlist]
len(datasimple)

1560

In [22]:
def countnum(A,a):
    count=0
    for i in range(len(A)):
        if(A[i]==a):
            count=count+1
    return count       

In [23]:
numam=[]
for i in range(11):
    numam.append(countnum(datasimple,0+0.1*i))
print(numam)    

[138, 0, 1, 0, 0, 683, 0, 0, 171, 387, 134]
