In [1]:
import pandas as pd
import numpy as np

In [2]:
# use the second file
data1_1 = pd.read_csv("20220808-FULL-1_1.csv", sep=';')
# display the data
data1_1

C:\Users\JXN19\AppData\Local\Temp/ipykernel_21784/1951926038.py:2: DtypeWarning: Columns (5,36,86,89) have mixed types. Specify dtype option on import or set low_memory=False.
  data1_1 = pd.read_csv("20220808-FULL-1_1.csv", sep=';')


fileGenerationDate  Entity_LogicalId Entity_EU_ReferenceNumber  \
0             08/08/2022                13                  EU.27.28   
1             08/08/2022                13                  EU.27.28   
2             08/08/2022                13                  EU.27.28   
3             08/08/2022                13                  EU.27.28   
4             08/08/2022                13                  EU.27.28   
...                  ...               ...                       ...   
21790         08/08/2022            143389                EU.8692.54   
21791         08/08/2022            143389                EU.8692.54   
21792         08/08/2022            143389                EU.8692.54   
21793         08/08/2022            143389                EU.8692.54   
21794         08/08/2022            143389                EU.8692.54   

      Entity_UnitedNationId Entity_DesignationDate Entity_DesignationDetails  \
0                       NaN                    NaN                       NaN   
1                       NaN                    NaN                       NaN   
2                       NaN                    NaN                       NaN   
3                       NaN                    NaN                       NaN   
4                       NaN                    NaN                       NaN   
...                     ...                    ...                       ...   
21790                   NaN             2022-07-21                       NaN   
21791                   NaN             2022-07-21                       NaN   
21792                   NaN             2022-07-21                       NaN   
21793                   NaN             2022-07-21                       NaN   
21794                   NaN             2022-07-21                       NaN   

                              Entity_Remark Entity_SubjectType  \
0                    (UNSC RESOLUTION 1483)                  P   
1                    (UNSC RESOLUTION 1483)                  P   
2                    (UNSC RESOLUTION 1483)                  P   
3                    (UNSC RESOLUTION 1483)                  P   
4                    (UNSC RESOLUTION 1483)                  P   
...                                     ...                ...   
21790  (Date of UN designation: 2022-07-21)                  P   
21791  (Date of UN designation: 2022-07-21)                  P   
21792  (Date of UN designation: 2022-07-21)                  P   
21793  (Date of UN designation: 2022-07-21)                  P   
21794  (Date of UN designation: 2022-07-21)                  P   

      Entity_SubjectType_ClassificationCode Entity_Regulation_Type  ...  \
0                                    person             regulation  ...   
1                                    person             regulation  ...   
2                                    person             regulation  ...   
3                                    person             regulation  ...   
4                                    person             regulation  ...   
...                                     ...                    ...  ...   
21790                                person              amendment  ...   
21791                                person              amendment  ...   
21792                                person              amendment  ...   
21793                                person              amendment  ...   
21794                                person              amendment  ...   

      Citizenship_LogicalId Citizenship_RegulationLanguage Citizenship_Remark  \
0                       NaN                            NaN                NaN   
1                       NaN                            NaN                NaN   
2                       NaN                            NaN                NaN   
3                       NaN                            NaN                NaN   
4                       1.0                             EN                NaN   


In [3]:
# get the whole name attribute
whole_name = data1_1['NameAlias_WholeName']

In [4]:
def cp(C,D):
    cend=[]
    a=-1
    b=-1
    m=-1
    n=-1
    target=-1
    if C==''and D=='':
        s=0
    elif C=='':
        s=0
    elif D=='':
        s=1    
    else:
        for i in range(len(C)):
            t=1
            for j in range(len(D)):
                if C[i]== D[j]:
                    a=i
                    b=j
                    m=a
                    n=b
                while m < len(C) and n<len(D) and C[a:m+1]==D[b:n+1]:
                    m=m+1
                    n=n+1
                long=m-a
                if long >= t:
                    t = long
                    target = m
            
            x=target-1
            y=n-1
            if b <len(D) and C[i]==D[b] :
                cend.append(x)
            else:
                cend.append(i)
        s_AB = len(set(cend))
        z = C.find(D);
        if z!=-1:
            ss=s_AB-1;
        else:
            ss = s_AB
        s=ss/len(C)    
    return s     

In [5]:
def distCPD(C,D):
    s1 = cp(C,D);
    s2 = cp(D,C);
    dist = 0.5*(s1+s2);
    return dist

In [6]:
len(whole_name)

21795

In [7]:
# so I replaced them with empty strings
whole_name.fillna('', inplace=True)
whole_name

0             Saddam Hussein Al-Tikriti
1                               Abu Ali
2                              Abou Ali
3                                      
4                                      
                      ...              
21790       Евгений Витальевич БАЛИЦКИЙ
21791    Yevgeniy Vitalievich BALYTSKIY
21792    Jevgenij Vitaljevitj BALITSKIJ
21793                                  
21794                                  
Name: NameAlias_WholeName, Length: 21795, dtype: object

In [8]:
import numpy as np
index = [i for i in range(len(whole_name))] # test_data为测试数据
np.random.shuffle(index) # 打乱索引
train_data = whole_name[index]

In [9]:
train_data

5696                  Rafeeq CHAHADE
20792                               
7761              Aamir Ali Chaudary
8152                     Hamid Masli
16051    Denis  Jurjevitj KHARITONOV
                    ...             
13410                    Hassan Ghul
2936                                
11606             Alshafee El-Sheikh
12885                               
2963                                
Name: NameAlias_WholeName, Length: 21795, dtype: object

In [10]:
# calculate all the distances in whole_name
length_train =  int(0.1*len(whole_name))
Name = np.zeros((length_train,length_train))
for i in range(length_train):
    for j in range(i+1,length_train):
        Name[i][j]=distCPD(train_data[i],train_data[j])

In [11]:
Name

array([[0.        , 0.72571429, 0.7725    , ..., 0.5       , 0.5       ,
        0.93833333],
       [0.        , 0.        , 0.33035714, ..., 0.5       , 0.5       ,
        0.88690476],
       [0.        , 0.        , 0.        , ..., 0.5       , 0.5       ,
        0.89583333],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.5       ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.5       ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [12]:
Name.shape

(2179, 2179)

In [13]:
index

[5696,
 20792,
 7761,
 8152,
 16051,
 9777,
 17504,
 17618,
 6124,
 11254,
 15355,
 11543,
 2950,
 18704,
 16077,
 11804,
 2294,
 5068,
 3785,
 18383,
 14295,
 1387,
 6932,
 21461,
 19852,
 11005,
 829,
 4298,
 10322,
 2103,
 13943,
 21742,
 16848,
 7058,
 18582,
 20016,
 4938,
 7121,
 21285,
 11846,
 15216,
 2096,
 11221,
 11270,
 3670,
 16865,
 2487,
 14962,
 5605,
 7579,
 3054,
 7720,
 7599,
 2553,
 9158,
 16397,
 3044,
 16935,
 1080,
 20639,
 10649,
 25,
 15597,
 8499,
 15168,
 3923,
 8413,
 17815,
 14970,
 9544,
 17005,
 9355,
 19110,
 13110,
 18008,
 18443,
 5922,
 127,
 5329,
 3284,
 19050,
 11851,
 7111,
 9309,
 17093,
 1012,
 18848,
 6973,
 6354,
 9582,
 3591,
 4420,
 17736,
 16947,
 8288,
 19006,
 3214,
 14939,
 12602,
 15286,
 10831,
 13484,
 10705,
 21771,
 17586,
 12539,
 1578,
 1261,
 12309,
 11865,
 14773,
 17467,
 6033,
 15083,
 20744,
 9195,
 3935,
 19810,
 13135,
 2413,
 9605,
 703,
 10437,
 4469,
 16405,
 6594,
 4845,
 3391,
 15112,
 7808,
 19909,
 982,
 15814,
 171,

In [14]:
entity=data1_1['Entity_LogicalId']
entity

0            13
1            13
2            13
3            13
4            13
          ...  
21790    143389
21791    143389
21792    143389
21793    143389
21794    143389
Name: Entity_LogicalId, Length: 21795, dtype: int64

In [15]:
entity_train=[]
for i in range(length_train):
    entity_train.append(entity[index[i]])

In [16]:
label = np.zeros((length_train,length_train))
for i in range(length_train):
    for j in range(i+1,length_train):
        if entity_train[i]==entity_train[j]:
            label[i][j]=0
        else:
            label[i][j] =1
print(label)        

[[0. 1. 1. ... 1. 1. 1.]
 [0. 0. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]
 ...
 [0. 0. 0. ... 0. 1. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]]


In [17]:
np.count_nonzero(label[1])

2175

In [18]:
len(set(entity_train))

1470

In [19]:
distlist=[]
for i in range(length_train):
    for j in range(i+1,length_train):
        if label[i][j]==0:
            distlist.append(Name[i][j])
print(distlist)            

[0.9322222222222223, 0.8952380952380952, 0.7983193277310925, 0.5, 0.0, 0.5, 0.5, 0.5, 0.9606481481481481, 0.7638888888888888, 1.0, 0.5, 0.9285714285714286, 0.5, 0.8858225108225108, 0.9464285714285714, 0.9543650793650793, 0.9689849624060151, 0.7595238095238095, 0.5, 0.9277777777777778, 0.5, 0.8333333333333333, 0.0, 0.0, 0.5, 0.5, 0.0, 0.5, 0.9350104821802935, 0.8885714285714286, 0.8809523809523809, 0.856280193236715, 1.0, 0.5, 0.5, 0.8776223776223776, 0.5, 0.5, 0.8689075630252101, 0.9015151515151516, 0.5, 0.8487511563367253, 0.5, 0.8077803203661327, 0.5, 0.5, 0.5, 0.5, 0.0, 0.5, 0.0, 0.7318518518518519, 0.9041394335511983, 0.8425925925925926, 0.9520697167755992, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.8727344365642238, 0.5, 0.5, 0.0, 0.9282051282051282, 0.7924242424242425, 0.5, 0.0, 0.0, 0.5, 0.860248447204969, 0.5, 0.0, 0.5, 0.7487179487179487, 0.5, 0.5, 0.7, 0.9333333333333333, 0.5, 0.9470588235294117, 0.5, 0.9505376344086022, 0.5, 0.0, 0.5, 0.5, 0.8705882352941177, 1.0, 0.5, 0.5, 0.5, 0

In [20]:
sum(distlist)/len(distlist)

0.6338411287359219

In [23]:
datasimple=[round(i,1) for i in distlist]
len(datasimple)

1328

In [24]:
def countnum(A,a):
    count=0
    for i in range(len(A)):
        if(A[i]==a):
            count=count+1
    return count       

In [29]:
numam=[]
for i in range(11):
    numam.append(countnum(datasimple,0+0.1*i))
print(numam)    

[132, 0, 0, 0, 0, 570, 0, 0, 126, 339, 130]
