In [1]:
import pandas as pd
import numpy as np

In [2]:
# use the second file
data1_1 = pd.read_csv("20220808-FULL-1_1.csv", sep=';')
# display the data
data1_1

C:\Users\JXN19\AppData\Local\Temp/ipykernel_20292/1951926038.py:2: DtypeWarning: Columns (5,36,86,89) have mixed types. Specify dtype option on import or set low_memory=False.
  data1_1 = pd.read_csv("20220808-FULL-1_1.csv", sep=';')


fileGenerationDate  Entity_LogicalId Entity_EU_ReferenceNumber  \
0             08/08/2022                13                  EU.27.28   
1             08/08/2022                13                  EU.27.28   
2             08/08/2022                13                  EU.27.28   
3             08/08/2022                13                  EU.27.28   
4             08/08/2022                13                  EU.27.28   
...                  ...               ...                       ...   
21790         08/08/2022            143389                EU.8692.54   
21791         08/08/2022            143389                EU.8692.54   
21792         08/08/2022            143389                EU.8692.54   
21793         08/08/2022            143389                EU.8692.54   
21794         08/08/2022            143389                EU.8692.54   

      Entity_UnitedNationId Entity_DesignationDate Entity_DesignationDetails  \
0                       NaN                    NaN                       NaN   
1                       NaN                    NaN                       NaN   
2                       NaN                    NaN                       NaN   
3                       NaN                    NaN                       NaN   
4                       NaN                    NaN                       NaN   
...                     ...                    ...                       ...   
21790                   NaN             2022-07-21                       NaN   
21791                   NaN             2022-07-21                       NaN   
21792                   NaN             2022-07-21                       NaN   
21793                   NaN             2022-07-21                       NaN   
21794                   NaN             2022-07-21                       NaN   

                              Entity_Remark Entity_SubjectType  \
0                    (UNSC RESOLUTION 1483)                  P   
1                    (UNSC RESOLUTION 1483)                  P   
2                    (UNSC RESOLUTION 1483)                  P   
3                    (UNSC RESOLUTION 1483)                  P   
4                    (UNSC RESOLUTION 1483)                  P   
...                                     ...                ...   
21790  (Date of UN designation: 2022-07-21)                  P   
21791  (Date of UN designation: 2022-07-21)                  P   
21792  (Date of UN designation: 2022-07-21)                  P   
21793  (Date of UN designation: 2022-07-21)                  P   
21794  (Date of UN designation: 2022-07-21)                  P   

      Entity_SubjectType_ClassificationCode Entity_Regulation_Type  ...  \
0                                    person             regulation  ...   
1                                    person             regulation  ...   
2                                    person             regulation  ...   
3                                    person             regulation  ...   
4                                    person             regulation  ...   
...                                     ...                    ...  ...   
21790                                person              amendment  ...   
21791                                person              amendment  ...   
21792                                person              amendment  ...   
21793                                person              amendment  ...   
21794                                person              amendment  ...   

      Citizenship_LogicalId Citizenship_RegulationLanguage Citizenship_Remark  \
0                       NaN                            NaN                NaN   
1                       NaN                            NaN                NaN   
2                       NaN                            NaN                NaN   
3                       NaN                            NaN                NaN   
4                       1.0                             EN                NaN   


In [3]:
# get the whole name attribute
whole_name = data1_1['NameAlias_WholeName']

In [4]:
def cp(C,D):
    cend=[]
    a=-1
    b=-1
    m=-1
    n=-1
    target=-1
    if C==''and D=='':
        s=0
    elif C=='':
        s=0
    elif D=='':
        s=1    
    else:
        for i in range(len(C)):
            t=1
            for j in range(len(D)):
                if C[i]== D[j]:
                    a=i
                    b=j
                    m=a
                    n=b
                while m < len(C) and n<len(D) and C[a:m+1]==D[b:n+1]:
                    m=m+1
                    n=n+1
                long=m-a
                if long >= t:
                    t = long
                    target = m
            
            x=target-1
            y=n-1
            if b <len(D) and C[i]==D[b] :
                cend.append(x)
            else:
                cend.append(i)
        s_AB = len(set(cend))
        z = C.find(D);
        if z!=-1:
            ss=s_AB-1;
        else:
            ss = s_AB
        s=ss/len(C)    
    return s     

In [5]:
def distCPD(C,D):
    s1 = cp(C,D);
    s2 = cp(D,C);
    dist = 0.5*(s1+s2);
    return dist

In [6]:
len(whole_name)

21795

In [7]:
# so I replaced them with empty strings
whole_name.fillna('', inplace=True)
whole_name

0             Saddam Hussein Al-Tikriti
1                               Abu Ali
2                              Abou Ali
3                                      
4                                      
                      ...              
21790       Евгений Витальевич БАЛИЦКИЙ
21791    Yevgeniy Vitalievich BALYTSKIY
21792    Jevgenij Vitaljevitj BALITSKIJ
21793                                  
21794                                  
Name: NameAlias_WholeName, Length: 21795, dtype: object

In [8]:
import numpy as np
index = [i for i in range(len(whole_name))] # test_data为测试数据
np.random.shuffle(index) # 打乱索引
train_data = whole_name[index]

In [9]:
train_data

18680                          Владимир Сергеевич КИРИЕНКО
9662                                 Mohamed Amer  MARDINI
8432                              Roman Viktorovich LYAGIN
182                                Huda Salih Mahdi Ammash
10063                             Zaur Raufovych ISMAYILOV
                               ...                        
2128                                          Arfauni Imad
9717                            Serhij Jurijovytj KOZIAKOV
13698    State Scientific Research Institute for Organi...
8889                                      »Brigade Vostok«
869                         Islamic Movement of Uzbekistan
Name: NameAlias_WholeName, Length: 21795, dtype: object

In [10]:
# calculate all the distances in whole_name
length_train =  int(0.1*len(whole_name))
Name = np.zeros((length_train,length_train))
for i in range(length_train):
    for j in range(i+1,length_train):
        Name[i][j]=distCPD(train_data[i],train_data[j])

In [11]:
Name

array([[0.        , 0.72571429, 0.7725    , ..., 0.5       , 0.5       ,
        0.93833333],
       [0.        , 0.        , 0.33035714, ..., 0.5       , 0.5       ,
        0.88690476],
       [0.        , 0.        , 0.        , ..., 0.5       , 0.5       ,
        0.89583333],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.5       ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.5       ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [12]:
Name.shape

(2179, 2179)

In [13]:
index

[18680,
 9662,
 8432,
 182,
 10063,
 17953,
 10126,
 6981,
 10109,
 20641,
 7475,
 11025,
 8474,
 6817,
 21772,
 16542,
 6895,
 1323,
 16963,
 19298,
 15734,
 18359,
 1397,
 14830,
 20194,
 675,
 18876,
 16750,
 13966,
 14687,
 14897,
 18454,
 5808,
 1476,
 4276,
 18783,
 4831,
 2809,
 18472,
 16342,
 8826,
 11193,
 11864,
 21133,
 8504,
 1334,
 14001,
 17942,
 17359,
 16826,
 17946,
 2560,
 16543,
 14332,
 13472,
 4722,
 16068,
 13785,
 10899,
 14065,
 2314,
 11809,
 4515,
 2280,
 11662,
 19081,
 13615,
 8094,
 11218,
 3665,
 10720,
 259,
 5965,
 6196,
 780,
 9161,
 17888,
 14786,
 15498,
 10363,
 14335,
 11991,
 4804,
 9928,
 12185,
 1084,
 12456,
 18591,
 17088,
 3904,
 15200,
 8154,
 7177,
 8059,
 20162,
 20405,
 17686,
 13217,
 2170,
 8448,
 2999,
 16479,
 15178,
 10571,
 12711,
 11490,
 13833,
 9398,
 17811,
 8162,
 14722,
 17365,
 4899,
 7412,
 10425,
 21652,
 11408,
 8961,
 13681,
 2507,
 20252,
 10144,
 13387,
 14360,
 4185,
 8427,
 2272,
 11464,
 12687,
 15598,
 19343,
 467,


In [14]:
entity=data1_1['Entity_LogicalId']
entity

0            13
1            13
2            13
3            13
4            13
          ...  
21790    143389
21791    143389
21792    143389
21793    143389
21794    143389
Name: Entity_LogicalId, Length: 21795, dtype: int64

In [15]:
entity_train=[]
for i in range(length_train):
    entity_train.append(entity[index[i]])

In [16]:
label = np.zeros((length_train,length_train))
for i in range(length_train):
    for j in range(i+1,length_train):
        if entity_train[i]==entity_train[j]:
            label[i][j]=0
        else:
            label[i][j] =1
print(label)        

[[0. 1. 1. ... 1. 1. 1.]
 [0. 0. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]
 ...
 [0. 0. 0. ... 0. 1. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]]


In [17]:
np.count_nonzero(label[1])

2177

In [18]:
len(set(entity_train))

1495

In [19]:
distlist=[]
for i in range(length_train):
    for j in range(i+1,length_train):
        if label[i][j]==0:
            distlist.append(Name[i][j])
print(distlist)            

[0.5, 0.5, 0.5, 0.0, 0.5, 0.5, 0.5, 0.5791666666666666, 0.5, 0.9641025641025641, 0.907843137254902, 0.5, 0.8757575757575757, 0.767948717948718, 0.9321839080459771, 0.5, 0.0, 0.0, 0.5, 0.5, 0.5, 0.9150326797385621, 0.9044444444444444, 0.7735042735042735, 0.8174603174603174, 0.9058441558441559, 0.5, 0.9619047619047618, 0.7673160173160173, 0.7871148459383753, 0.5, 0.9277777777777778, 0.5, 0.9136904761904762, 0.5, 1.0, 0.5, 0.5, 0.8362573099415205, 0.905982905982906, 0.5, 0.9449404761904762, 0.8484848484848485, 0.5, 0.0, 0.5, 0.0, 0.0, 0.0, 0.8333333333333333, 1.0, 0.0, 0.8847826086956522, 0.0, 0.5, 0.7889863547758285, 0.8164983164983165, 0.5, 0.7602836879432624, 0.5, 0.5, 0.5, 0.5, 0.8590909090909091, 0.9212121212121211, 0.8893939393939394, 0.930952380952381, 0.8323529411764705, 0.5, 0.8309523809523809, 0.5, 0.5, 0.5, 0.5, 0.0, 0.0, 0.5, 0.5, 0.5, 0.0, 0.0, 0.5, 0.8991134751773049, 0.5, 0.5, 0.5, 0.5, 0.0, 0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.9307359307359306, 0.8597883597883598

In [20]:
sum(distlist)/len(distlist)

0.6451739640447893

In [21]:
datasimple=[round(i,1) for i in distlist]
len(datasimple)

1235

In [22]:
def countnum(A,a):
    count=0
    for i in range(len(A)):
        if(A[i]==a):
            count=count+1
    return count       

In [23]:
numam=[]
for i in range(11):
    numam.append(countnum(datasimple,0+0.1*i))
print(numam)    

[110, 0, 0, 0, 1, 526, 0, 0, 100, 345, 119]


In [30]:
Name.shape

(2179, 2179)

In [32]:
undistlist=[]
for m in range(length_train):
    for n in range(m+1,length_train):
        if label[m][n]==1:
            undistlist.append(Name[m][n])
print(len(undistlist)) 

2371696


In [25]:
undatasimple=[round(i,1) for i in undistlist]
undistam=[]
for i in range(11):
    undistam.append(countnum(undatasimple,0+0.1*i))
print(undistam)  

[230141, 140, 302, 0, 1342, 1022310, 0, 0, 210860, 619445, 228546]
